<header>
    <nav>
        <div><a href="http://34.71.144.13:8888/javalab-summer-project-0.0.1/profile/">Профиль</a></div>
        <div><a href="http://34.71.144.13:8888/javalab-summer-project-0.0.1/resumes">Ваши Резюме</a></div>
        <div><a href="http://34.71.144.13:8888/javalab-summer-project-0.0.1/vacancy">Вакансии</a></div>
        <div><a href="http://34.71.144.13:8888/javalab-summer-project-0.0.1/portfolios/">Портфолио</a></div>
    </nav>
</header>