<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Страница не найдена!</title>
    <#include "common/head-common.ftlh">
    <link rel="stylesheet" type="text/css" href="/css/common.css">
</head>

<body class="body h-100">
<#include "header.ftlh">
<br>
<div class="container">
    <div class="row">
        <div class="col-1"></div>
        <div class="col-10 d-flex align-items-center justify-content-center" style="height: calc(100vh - 40vh)">
            <p class="h1">404 - Упс! Похоже такой страницы не существует!</p>
        </div>
        <div class="col-1"></div>
    </div>
</div>
</body>

</html>