<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Начальная страница</title>
    <#include "common/head-common.ftlh"/>
    <link rel="stylesheet" href="http://34.71.144.13:8888/javalab-summer-project-0.0.1/css/common.css" type="text/css">
</head>
<body class="body">
<#include "header.ftlh">
<br>
<div class="container">
    <div class="row">
        <div class="col-1"></div>
        <div class="col-10 d-flex align-items-center justify-content-center flex-column" style="height: calc(100vh - 40vh)">
            <p class="h1">⬈⬈⬈</p>
            <p class="h1">Чтобы воспользоваться сайтом, пожалуйста, войдите в аккаунт </p>
            <p class="h1">⬈⬈⬈</p>
        </div>
        <div class="col-1"></div>
    </div>
</div>
</body>
</html>